server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Student?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  messages:
    basename: base
  mail:
    default-encoding: UTF-8
    host: romijatmiko033.gmail.com
    username: romijatmiko033@gmail.com
    password: vjvccruvgqowfrsw
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 30000
          timeout: 30000
    protocol: smtp
    test-connection: false
